name: workout_memo_timer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1

  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  flutter_use: ^0.0.3

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  stop_watch_timer: ^2.0.0

  intl: ^0.18.1

  cupertino_icons: ^1.0.2
  flutter_gradients: ^1.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5

  freezed: ^2.3.3
  json_serializable: ^6.6.2

  drift_dev: ^2.8.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
